### ISSUE TITLE
Gutenberg Project CD(-sized) set

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#61]
_From @run-dey on July 18, 2018 16:18_

I see that this page is being used for data issues.

There is a complete set of English Gutenberg books on kiwix.org, which is great, but it is also prohibitively big (50+ GB).

But there has also been released a 'best of' Gutenberg CD. It would be a great option for smaller devices, and would certainly be appreciated by many people.

http://www.gutenberg.org/wiki/Gutenberg%3AThe_CD_and_DVD_Project

I would have made the ZIM file myself from the HTML/text files, but unfortunately I am not in the position to do so at the moment.

Thank you.

Sent from a disposable GitHub account.

_Copied from original issue: kiwix/overview#7_

**Comment by kelson42** [comment]
We Could probably provide ZIM file corresponding to the DVD/CD issue. That should be quite easy with zimwriterfs.

**Comment by run-dey** [comment]
Yes, I had looked into zimwriterfs, but unfortunately I had trouble getting it to work (which wasn't its fault, but rather the fault of my rather unusual setup at the moment).

Please consider making the CD version first, rather than the DVD one. I imagine that such a core selection would be mostly used by people who just want to have something to read recreationally in a free moment, as opposed to literary research, so comprehensiveness of the collection isn't really the issue either way, while max portability would help. The CD version has lots of titles anyway.

**Comment by benoit74** [comment]
@kelson42 can we close this issue?
- we are in 2023, 5 years about original issue
- CDs/DVDs have almost disappeared and SD cards are becoming cheaper than ever
- original project seems to have disappeared, last online page seems to be https://www.gutenberg.org/files/11220/cd-dvd-readme.txt

**Comment by kelson42** [comment]
@benoit74 Agree, is advantageously superseeded by #184 anyway.
